config/routes.rb
Rails.application.routes.draw do

  root :to =>  'site#home_new'
  get  '/:name/:id.html'          => 'site#home_new', :as => :site_home_dentista

 # root :to => "static#index_for_now"
  
  devise_for :dentists, path: "dentista", 
    controllers: { sessions: "dentist/sessions", registrations: 'dentist/registrations' },   
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
        unlock: 'unlock', registration: 'register', sign_up: 'sign_up' } do
    
    authenticated :dentists do
      root 'dentists/registrations#edit', as: :authenticated_root #'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'dentists/sessions#new', as: :unauthenticated_root
    end
  end
  
  get  'dentista/payment/process/:dentista_id'          => 'dentist/payment#process_payment', :as => :payment_process_payment
  post  'dentista/payment/update_status'   => 'dentist/payment#update_status', :as => :payment_update_status
  get  'dentista/payment/redo_payment/:dentista_id'   => 'dentist/payment#redo_payment', :as => :redo_payment
  patch  'dentista/payment/process_redo_payment'   => 'dentist/payment#process_redo_payment', :as => :process_redo_payment

  devise_for :users
  
  devise_scope :user do
    authenticated :user do
      root 'admin/admin#index', as: :authenticated_root #'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  namespace :api do
    namespace :v1 do
     
      get  'dentista/:dentista_id'                    => 'dentistas#get'
      get  'dentistas/find_near'                      => 'dentistas#find_near'
      get  'dentistas/cidades'                        => 'dentistas#get_cities'
      get  'dentistas/bairros'                        => 'dentistas#get_neighborhood'
      get  'dentistas/servicos'                       => 'dentistas#get_servicos'
      get  'dentistas/find_filter'                    => 'dentistas#find_filter' 
      get  'nr_dentistas'                             => 'dentistas#count'

      get  'dica/get_all'                             => 'dicas#get_ultimas_dicas' 
      
    end
  end
   
   
  namespace :admin do
    get '' => 'admin#index' 
    get 'admin/index'
    
    #dentista
    get     'dentista' => 'dentista#index'
    get     'dentista/new'
    post    'dentista/create'
    get     'dentista/:id' => 'dentista#show', as: 'dentista_show'
    get     'dentista/:id/edit' => 'dentista#edit', as: 'dentista_edit'
    patch   'dentista/:id' => 'dentista#update', as: 'dentista_update_patch'
    put     'dentista/:id' => 'dentista#update', as: 'dentista_update_put'
    delete  'dentista/:id' => 'dentista#destroy', as: 'dentista_delete' 
    delete     'dentista/foto/:id/:id_image' => 'dentista#delete_foto', as: 'dentista_delete_foto' 
    
    #dica
    get     'dica' => 'dica#index'
    get     'dica/new'
    post    'dica/create'
    get     'dica/:id' => 'dica#show', as: 'dica_show'
    get     'dica/:id/edit' => 'dica#edit', as: 'dica_edit'
    patch   'dica/:id' => 'dica#update', as: 'dica_update_patch'
    put     'dica/:id' => 'dica#update', as: 'dica_update_put'
    delete  'dica/:id' => 'dica#destroy', as: 'dica_delete'
    
  end
end

app/models/dica.rb
class Dica
  include Mongoid::Document
  include Mongoid::Timestamps
  
  before_create :assign_id
  
  field :_id,                                         type: Integer
  field :dica,         as: :dica,                        type: String
  field :link,         as: :link,                        type: String
  belongs_to :dentista, class_name: "Dentist"
  
  field :dentista

  default_scope -> { order_by(:updated_at.desc) }

  def dentista
    if not self.dentista_id.nil? then
      return Dentist.only(:id, :nome, :icon).find(self.dentista_id)
    end
    return nil
  end
  
  private
    def assign_id
      self._id = Sequence.generate_id(:dica)
    end
end

app/controllers/admin/dica_controller.rb
class Admin::DicaController < ApplicationController
  before_action :authenticate_user!

  def show
    @dica = Dica.find(params[:id])
  end

  def edit
    @dica = Dica.find(params[:id])
  end

  def update
    @dica = Dica.find(params[:id])

    if @dica.update(dica_params)
      flash["alert alert-success"] = "Alteração efetuada com sucesso."
      redirect_to admin_dica_path
    else
      flash["alert alert-danger"] = "Ocorreu algum erro."
      render 'edit'
    end

  end

  def new
    @dica = Dica.new
  end

  def create
    @dica = Dica.new(dica_params)

    if @dica.save
      flash["alert alert-success"] = "Categoria salva."
      redirect_to admin_dica_path
    else
      flash["alert alert-danger"] = "Ocorreu algum erro."
      render "new"
    end
  end

  def index
    @dicas = Dica.all.order_by(:_id.asc)
  end

  def destroy
    @dica = Dica.find(params[:id])
    if not @dica.nil? then
    @dica.destroy
    end
    redirect_to admin_dica_path
  end

  def dica_params
    params.require(:dica).permit(:dica, :_id, :dentista_id)
  end
end

app/controllers/api/v1/dicas_controller.rb
class Api::V1::DicasController < ApplicationController

  respond_to :json
  
  #Retorna dados da dica
  # http://dentistasdds.dev.com/api/v1/dentista/545a5e0c52616e29a8010000.json
  def get
    dica_id = params[:dica_id]
    if dica_id.nil? or dica_id.empty? then
        respond_to do |format|
          format.json { render :json => {:success => false,
                                         :info => "Parâmetros inválidos!"} }
        end
    else
      dica = Dica.find(dica_id)
      
      respond_to do |format|
        format.json { render :json => {:success => true,
                                       :dica => dica}
                                       }
      end
    end
  end
  
   
  def get_ultimas_dicas
      page = params[:page] || 1
      dica = Dica.order_by(:updated_at.desc).limit(MainYetting.DEFAULT_REG_PER_PAGE).skip((page.to_i-1) * MainYetting.DEFAULT_REG_PER_PAGE)
      
      respond_to do |format|
        format.json { render :json => {:success => true,
                                       :dicas => dica,
                                       :reg_pag => MainYetting.DEFAULT_REG_PER_PAGE}
                                     }
      end
    
  end
  
end

app/helpers/admin/dica_helper.rb
module Admin::DicaHelper
end

app/views/admin/dica/edit.html.erb
<%= render :template => "admin/header", :locals => {:titulo => "Dicas", :sub_titulo => "Editar"} %>

<%= form_for @dica, url: { action: "update" } , html: {:multipart => true} do |f| %>
	<%= f.hidden_field :_id %>
	<div class="form-group">
		<%= f.label :dica %>
		<%= f.text_area :dica, size: 80, maxlength: 200,required: true, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label "Dentista" %>
	
		<% @dentistas =Dentist.where(:active => true, :dt_expiration_date.gte => Date.today()).order_by(:nome.asc) %>
		<%= select_tag "dica[dentista_id]", options_from_collection_for_select(@dentistas, "id", "nome", @dica.dentista_id), include_blank: true,  class: 'form-control form-control-no-width'%>
	</div>
	<div class="form-group">
		<%= f.submit "Salvar" %>
	</div>

<% end %>

app/views/admin/dica/index.html.erb
<%= render :template => "admin/header", :locals => {:titulo => "Dicas", :sub_titulo => "Lista"} %>

<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>ID</th>
			<th>Dica</th>
			<th>Dentista</th>
			<th colspan="3">Ação</th>
		</tr>
	</thead>
	<tbody>
		<% @dicas.each do |dica| %>
		<tr>
			<td><%= dica._id %></td>
			<td><%= dica.dica %></td>
			<td><%= dica.dentista.nil? ? "" : dica.dentista.nome %></td>
			<td><%= link_to 'Visualizar', admin_dica_show_path(dica) %></td>
			<td><%= link_to 'Editar', admin_dica_edit_path(dica) %></td>
			<td><%= link_to 'Apagar', admin_dica_delete_path(dica), method: :delete, data: { confirm: 'Tem certeza que deseja apagar?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/dica/new.html.erb
<%= render :template => "admin/header", :locals => {:titulo => "Dicas", :sub_titulo => "Cadastrar"} %>

<%= form_for @dica, url: { action: "create" } , html: {:multipart => true} do |f| %>

	<div class="form-group">
		<%= f.label :dica %>
		<%= f.text_area :dica, size: 80, maxlength: 200,required: true, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label "Dentista" %>
	
		<% @dentistas =Dentist.where(:active => true, :dt_expiration_date.gte => Date.today()).order_by(:nome.asc) %>
		<%= select_tag "dica[dentista_id]", options_from_collection_for_select(@dentistas, "id", "nome", @dica.dentista_id), include_blank: true,  class: 'form-control form-control-no-width'%>
	</div>
	<div class="form-group">
		<%= f.submit "Salvar" %>
	</div>

<% end %>

app/views/admin/dica/show.html.erb
<%= render :template => "admin/header", :locals => {:titulo => "Dicas", :sub_titulo => "Visualizar"} %>

<div class="form-group">
	<label>Id: </label>
	<%= @dica._id%>
</div>

<div class="form-group">
	<label>Dica: </label>
	<%= @dica.dica%>
</div>

<div class="form-group">
	<label>Dentista: </label>
	<%= @dica.dentista.nil? ? " - " : @dica.dentista.nome%>
</div>