config/routes.rb
Rails.application.routes.draw do

  root :to =>  'site#home_new'
  get  '/:name/:id.html'          => 'site#home_new', :as => :site_home_dentista

 # root :to => "static#index_for_now"
  
  devise_for :dentists, path: "dentista", 
    controllers: { sessions: "dentist/sessions", registrations: 'dentist/registrations' },   
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
        unlock: 'unlock', registration: 'register', sign_up: 'sign_up' } do
    
    authenticated :dentists do
      root 'dentists/registrations#edit', as: :authenticated_root #'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'dentists/sessions#new', as: :unauthenticated_root
    end
  end
  
  get  'dentista/payment/process/:dentista_id'          => 'dentist/payment#process_payment', :as => :payment_process_payment
  post  'dentista/payment/update_status'   => 'dentist/payment#update_status', :as => :payment_update_status
  get  'dentista/payment/redo_payment/:dentista_id'   => 'dentist/payment#redo_payment', :as => :redo_payment
  patch  'dentista/payment/process_redo_payment'   => 'dentist/payment#process_redo_payment', :as => :process_redo_payment

  devise_for :users
  
  devise_scope :user do
    authenticated :user do
      root 'admin/admin#index', as: :authenticated_root #'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  namespace :api do
    namespace :v1 do
     
      get  'dentista/:dentista_id'                    => 'dentistas#get'
      get  'dentistas/find_near'                      => 'dentistas#find_near'
      get  'dentistas/cidades'                        => 'dentistas#get_cities'
      get  'dentistas/bairros'                        => 'dentistas#get_neighborhood'
      get  'dentistas/servicos'                       => 'dentistas#get_servicos'
      get  'dentistas/find_filter'                    => 'dentistas#find_filter' 
      get  'nr_dentistas'                             => 'dentistas#count'

      get  'dica/get_all'                             => 'dicas#get_ultimas_dicas' 
      
    end
  end
   
   
  namespace :admin do
    get '' => 'admin#index' 
    get 'admin/index'
    
    #dentista
    get     'dentista' => 'dentista#index'
    get     'dentista/new'
    post    'dentista/create'
    get     'dentista/:id' => 'dentista#show', as: 'dentista_show'
    get     'dentista/:id/edit' => 'dentista#edit', as: 'dentista_edit'
    patch   'dentista/:id' => 'dentista#update', as: 'dentista_update_patch'
    put     'dentista/:id' => 'dentista#update', as: 'dentista_update_put'
    delete  'dentista/:id' => 'dentista#destroy', as: 'dentista_delete' 
    delete     'dentista/foto/:id/:id_image' => 'dentista#delete_foto', as: 'dentista_delete_foto' 
    
    #dica
    get     'dica' => 'dica#index'
    get     'dica/new'
    post    'dica/create'
    get     'dica/:id' => 'dica#show', as: 'dica_show'
    get     'dica/:id/edit' => 'dica#edit', as: 'dica_edit'
    patch   'dica/:id' => 'dica#update', as: 'dica_update_patch'
    put     'dica/:id' => 'dica#update', as: 'dica_update_put'
    delete  'dica/:id' => 'dica#destroy', as: 'dica_delete'
    
  end
end

app/controllers/admin/dentista_controller.rb
class Admin::DentistaController < ApplicationController

  include Dentist::DentistHelper

  before_action :authenticate_user!, except: [:delete_foto]

  skip_before_filter  :verify_authenticity_token


  def show
    @dentista = Dentist.find(params[:id])
  end

  def edit
    @dentista = Dentist.find(params[:id])
    
    build_dentista(@dentista)
  end

  def update
    @dentista = Dentist.find(params[:id])

    params_update = dentista_update_params
    has_promo = params[:dentist][:has_promo]
    if has_promo.nil? or 
      (not has_promo.nil? and has_promo == "0") then
      params_update[:promocao] = nil
    end
 
    params[:dentist].delete :has_promo
    
    if not params[:dentist][:has_at_emerg].nil? and params[:dentist][:has_at_emerg] == "0" then
      params_update[:at_emerg] = nil
    end
    params[:dentist].delete :has_at_emerg
    
    if params[:dentist][:at_emerg].nil? then
      params_update[:at_emerg] = nil
    end
    
    if @dentista.update(params_update)
      
      if params[:images]
        params[:images].each { |image|
          @dentista.pictures.create(picture: image)
        }
      end
      
      flash["alert alert-success"] = "Alteração efetuada com sucesso."
      redirect_to admin_dentista_path
    else
      set_error(@dentista, "Ocorreu algum erro.")      
      render 'edit'
    end

  end

  def new
    @dentista = Dentist.new
    build_dentista(@dentista)
  end

  def create
    pwd = SecureRandom.hex(8)
    params[:dentist][:password] = pwd
    params[:dentist]["password_confirmation"] = pwd
    
    if not params[:dentist][:has_promo].nil? and params[:dentist][:has_promo] == "0" then
      params[:dentist].delete :promocao
    end
    params[:dentist].delete :has_promo
    
    if not params[:dentist][:has_at_emerg].nil? and params[:dentist][:has_at_emerg] == "0" then
      params[:dentist].delete :at_emerg
    end
    params[:dentist].delete :has_at_emerg
    
    if params[:dentist][:at_emerg].nil? then
      params[:dentist][:at_emerg] = []
    end

    @dentista = Dentist.new(dentista_create_params)
    if @dentista.save
      #@dentista.pictures = []
      if params[:images]
        params[:images].each { |image|
          @dentista.pictures.create(picture: image)
        }
        #@dentista.save
      end
      
      flash["alert alert-success"] = "Alteração efetuada com sucesso."
      redirect_to admin_dentista_path
    else
      set_error(@dentista, "Ocorreu algum erro.")    
      build_dentista(@dentista) 
      render 'new'
    end
  end

  def index
    @dentistas = Dentist.unscoped.all.order_by(:id.asc)
  end

  def destroy
    @dentista = Dentist.find(params[:id])
    if not @dentista.nil? then
    @dentista.destroy
    end
    redirect_to admin_dentista_path
  end
  
  def delete_foto
    #verifica se o usuário ou dentista está logado
    if user_signed_in? or dentist_signed_in? then
      if dentist_signed_in? then
        @dentista = currrent_dentist
      else
        @dentista = Dentist.find(params[:id])
      end
      
      if delete_foto_helper(@dentista, params[:id_image].to_i) then
        flash["alert alert-success"] = "Foto deletada com sucesso."
      else
        set_error(@dentista, "Ocorreu algum erro.")
      end
      
      if user_signed_in? then
         redirect_to admin_dentista_edit_path(@dentista)
      else
         redirect_to edit_dentist_registration_path(@dentista)
      end
    else
      flash["alert alert-success"] = "Ocorreu algum erro."
      redirect_to root_path
    end
  end

  def dentista_update_params
    params.require(:dentist).permit(:active, :dt_expiration_date, :_id, :nome, :site, :email, :profile, :icon, :destaque, :phones => [], :equipe => [], :servicos => [], #:at_normal => [], 
    address: [:street, :number, :complement, :neighborhood, :zip_code, :city, :state], 
    promocao: [:perc, :servico], at_normal: [:dia_sem, :h_open, :h_close], at_emerg: [:dia_sem, :h_open, :h_close])
  end
  
  def dentista_create_params
    params.require(:dentist).permit(:active, :dt_expiration_date, :password, "password_confirmation", :_id, :nome, :site, :email, :profile, :icon, :destaque, :phones => [], :equipe => [], :servicos => [], 
    address: [:street, :number, :complement, :neighborhood, :zip_code, :city, :state], promocao: [:perc, :servico], at_normal: [:dia_sem, :h_open, :h_close], at_emerg: [:dia_sem, :h_open, :h_close])
  end
  
  private
    def get_photo_filename(file_name)
      extn = File.extname  file_name 
      return SecureRandom.uuid + extn
    end
    
    def get_foto_file_name(uploaded_io)
      file_name = nil
      if not uploaded_io.nil? then
        img = MiniMagick::Image.open(uploaded_io.path)
        puts "******** >>>> #{img[:width]} x  #{img[:height]}"
        file_name = get_photo_filename(uploaded_io.original_filename)     
      end
      
      if not uploaded_io.nil? then
        #File.open(Rails.root.join('public', 'upload', "#{file_name}"), 'wb') do |file|
        directory = MainYetting.PATH_UPLOAD_IMGS
        File.open(File.join(directory, "#{file_name}"), 'wb') do |file|
          file.write(uploaded_io.read)
        end
        return "/upload/#{file_name}"  
      end
      
      return nil
           
    end
    
    def set_error(obj, msg)
      if not obj.errors.nil? then
        flash["alert alert-danger"] = obj.errors.full_messages
      else
        flash["alert alert-danger"] = msg
      end
    end
    
    def build_dentista(dentista)
      if dentista.address.nil? then
        dentista.address = Address.new
      end
      if dentista.promocao.nil? then
        dentista.promocao = Promocao.new
      end
      if dentista.at_normal.nil? or dentista.at_normal.size <= 0  then
        dentista.at_normal.build
      end
    
      if dentista.at_emerg.nil? or dentista.at_emerg.size <= 0  then
        dentista.at_emerg.build
      end
    end
end

app/controllers/api/v1/dentistas_controller.rb
class Api::V1::DentistasController < ApplicationController

  respond_to :json
  
  #before_action :authenticate_user!
  
  #Retorna dados do bar
  # http://dentistasapp.dev.com/api/v1/dentista/545a5e0c52616e29a8010000.json
  def get
    dentista_id = params[:dentista_id]
    if dentista_id.nil? or dentista_id.empty? then
        respond_to do |format|
          format.json { render :json => {:success => false,
                                         :info => "Parâmetros inválidos!"} }
        end
    else
      dentista = Dentist.find(dentista_id)
      
      respond_to do |format|
        format.json { render :json => {:success => true,
                                       :dentista => dentista.as_json()}
                                       }
      end
    end
  end
  
    
  #Retorna os bares com os pacotes próximos
  # curl http://dentistasapp.herokuapp.com/api/v1/nr_dentistas.json
  def count
    respond_to do |format|
      format.json { render :json => {:success => true,
                                     :nr => Dentist.count} }
    end

  end

  # http://dentistasapp.herokuapp.com/api/v1/dentistas/find_near.json?lat=-23.56033&lng=-46.58301
  def find_filter
    
    cidade = params[:cidade]
    estado = params[:estado]
    bairro = params[:bairro]
    nome = params[:nome]
    servico = params[:servico]
    emergencia = params[:emergencia]
    promo = params[:promo] || params[:promocao]
    lat = params[:lat]
    lng = params[:lng]
    
    page = params[:page]
    if page.nil? then 
      page = "1"
    end
    
    expressions = []
    query = Dentist.all
    expressions.push({ "active" => true})
    expressions.push({ "dt_expiration_date" => {"$gte" => Date.today()}})
    
    if not nome.nil? and not nome.empty? then
      nome = ActiveSupport::Inflector.transliterate(nome)
      nome = make_search_exp(nome)
      query = query.or({:nome => /.*#{nome}.*/i} , {:"equipe" => {"$in" => [/.*#{nome}.*/i]}  } )
      expressions.push({ "$or" => [ {"nome" => /.*#{nome}.*/i}, {"equipe" => {"$in" => [/.*#{nome}.*/i]}  } ] })
    end

    if not cidade.nil? and not cidade.empty? then
      cidade = ActiveSupport::Inflector.transliterate(cidade)
      cidade = make_search_exp(cidade)
      query = query.where("address.city" => /.*#{cidade}.*/i) 
      expressions.push({ "address.city" => /.*#{cidade}.*/i })
    end
    
    if not bairro.nil? and not bairro.empty? then
      bairro = ActiveSupport::Inflector.transliterate(bairro)
      bairro = make_search_exp(bairro)
      query = query.where("address.neighborhood" => /.*#{bairro}.*/i) 
      expressions.push({ "address.neighborhood" => /.*#{bairro}.*/i })
    end
    
    if not servico.nil? and not servico.empty? then
      servico = ActiveSupport::Inflector.transliterate(servico)
      servico = make_search_exp(servico)
      query = query.in("servicos" => [/.*#{servico}.*/i]) 
      expressions.push({ "servicos" =>  {"$in" => [/.*#{servico}.*/i]} })
      
     
    end

    
    if not emergencia.nil? and not emergencia.empty? and emergencia == "true" then
      query = query.exists(:"at_emerg" => true) 
      expressions.push({ "at_emerg" => {"$exists" => true}})
    end
    
    if not promo.nil? and not promo.empty? and promo == "true" then
      query = query.exists(:"promo" => true) 
      expressions.push({ "promo" => {"$exists" => true}})
    end
   
    queryJson = nil
    if not expressions.nil? and expressions.size > 0 then
      queryJson = { "$and" => expressions }
    end

    @dentistas = nil
    if lng.nil? or lng.empty? or lat.nil? or lat.empty? then
      per_page = MainYetting.DEFAULT_REG_PER_PAGE
      skip = ((page.to_i - 1) * per_page)
      @dentistas = Dentist.where(queryJson).limit(per_page).skip(skip)
    else 
      @dentistas = Dentist.find_near( [lng.to_f, lat.to_f], params[:page], queryJson)
    end
    
    #dentistas = Dentist.only(:id, :name, :ph, :pr, :geo_near_distance, :coordinates, :address)
    #            .for_js("this.n = p_nome", p_nome: "#{nome}")
                
    respond_to do |format|
        format.json { render :json => {:success => true, 
                                        :dentistas => @dentistas.as_json( 
                                             :base_info =>  true),
                                        :reg_pag => MainYetting.DEFAULT_REG_PER_PAGE}}
      end
    
  end
  
  #Retorna os bares com os pacotes próximos
  # curl http://dentistasapp.herokuapp.com/api/v1/dentistas/find_near.json?lat=-23.56033&lng=-46.58301
  def find_near

    lat = params[:lat]
    lng = params[:lng]
    page = params[:page]
    
    if params[:page].nil? then 
      page = 1
    else
      page = params[:page].to_i
    end
    
    if lat.nil? or lng.nil? then
        respond_to do |format|
          format.json { render :json => {:success => false,
                                         :info => "Parâmetros inválidos"} }
        end
    else 
      @location = [lng.to_f, lat.to_f]
        
      #   dentistas = Dentista
      #          .only(:id, :nome, :phones, :profile, :geo_near_distance, :coordinates, :address)
      #          .limit(MainYetting.DEFAULT_REG_PER_PAGE_DIST)
      #          .geo_near(@location).max_distance(MainYetting.DEFAULT_KM_FIND_NEAR/6378.137)
      #          .spherical.distance_multiplier(6378.137)
               
      expressions = [] 
      expressions.push({ "active" => true})
      expressions.push({ "dt_expiration_date" => {"$gte" => Date.today()}})
      queryJson = { "$and" => expressions }
    
      dentistas = Dentist.find_near( [lng.to_f, lat.to_f], params[:page], queryJson)

      respond_to do |format|
        format.json { render :json => {:success => true, 
                                        :dentistas => dentistas.as_json(:base_info =>  true), 
                                        :reg_pag => MainYetting.DEFAULT_REG_PER_PAGE}}
      end
    end
  end
  
  def get_cities()
    cidades = Dentist.distinct("address.city")
    respond_to do |format|
      format.json { render :json => {:success => true, 
                                      :values => cidades}}
    end
  end

  def get_neighborhood()
    bairros = Dentist.where("address.city" => params[:city]).distinct("address.neighborhood")
    respond_to do |format|
      format.json { render :json => {:success => true, 
                                        :values => bairros}}
    end
  end

  def get_servicos()
    servicos = MainYettings.SERVICOS
    
    
    respond_to do |format|
      format.json { render :json => {:success => true, 
                                        :values => servicos}}
    end
  end
  
  def make_search_exp(str)
     n = str.downcase.strip.to_s
     n.gsub!("a",    '[aàãá]')
     n.gsub!("e",    '[eéê]')
     n.gsub!("i",    '[ií]')
     n.gsub!("o",    '[oó]')
     n.gsub!("u",    '[uú]')
     n.gsub!("c",    '[cç]')
     n
  end
  
end

app/helpers/admin/dentista_helper.rb
module Admin::DentistaHelper
end

app/views/admin/dentista/index.html.erb
<%= render :template => "admin/header", :locals => {:titulo => "Dentistas", :sub_titulo => "Lista"} %>

<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>ID</th>
			<th>Nome</th>
			<th>Ativo</th>
			<th>Venc. Assinatura</th>
			<th colspan="3">Ação</th>
		</tr>
	</thead>
	<tbody>
		<% @dentistas.each do |obj| %>
		<tr>
			<td><%= obj._id %></td>
			<td><%= obj.nome%></td>
			<td><%= obj.active ? "Sim" : "Não"  %></td>
			<td><%= obj.dt_expiration_date_format  %></td>
			<td><%= link_to 'Visualizar', admin_dentista_show_path(obj) %></td>
			<td><%= link_to 'Editar', admin_dentista_edit_path(obj) %></td>
			<td><%= link_to 'Apagar', admin_dentista_delete_path(obj), method: :delete, data: { confirm: 'Tem certeza que deseja apagar?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/dentista/show.html.erb
<%= render :template => "admin/header", :locals => {:titulo => "Dentistas", :sub_titulo => "Visualizar"} %>

<div class="col-lg-12">
	<div class="panel panel-default">
   		<div class="panel-heading">
        	<h3 class="panel-title">Dados</h3>
        </div>
        <div class="panel-body">
        	<div class="form-group">
        		<%=image_tag(@dentista.profile, style: "max-height: 100px;")%>
        	</div>
        	<div class="form-group">
        		<label>Id:</label>
				<%=@dentista._id%>
			</div>
			<div class="form-group">
				<label>Nome:</label>
				<%=@dentista.nome%>
			</div>
			<div class="form-group">
				<label>Ativo:</label>
				<%= (@dentista.active ? "Sim" : "Não")%>
			</div>
			<div class="form-group">
				<label>Vencimento da Assinatura:</label>
				<%= @dentista.dt_expiration_date_format %>
			</div>
			
			<div class="form-group">
				<label>Ícone:</label>
				<%=@dentista.icon.nil? ? "" : image_tag(@dentista.icon, style: "max-height: 100px; padding:10px")%>
			</div>
			
			<div class="form-group">
				<label>Telefone:</label>
				<% @phone = (not @dentista.phones.nil? and @dentista.phones.size > 0) ? @dentista.phones[0] : ""%>
				<%=@phone%>
			</div>
			<div class="form-group">
				<label>Site:</label>
				<%=@dentista.site%>
			</div>
			<div class="form-group">
				<label>Email:</label>
				<%=@dentista.email%>
			</div>
			
			<div class="form-group">
				<label>Destaque:</label>
				<%=@dentista.destaque == 1 ? "Não" : "Sim"%>
			</div>
			<div class="form-group">
			</div>
			
		</div>
	</div>
</div>

<div class="col-lg-12">
	<div class="panel panel-default">
   		<div class="panel-heading">
        	<h3 class="panel-title">Serviços</h3>
        </div>
        <div class="panel-body">
        	
			<div class="form-group">
				<div class='col-lg-12-without-padding'>
			<%
			 		total_cat = @dentista.servicos.nil? ? 0 : @dentista.servicos.size
			      	num_p_col = total_cat / 3
			     	num = 0
			      	col = 1
			      	if num_p_col = 0 then
			      		num_p_col = 1
			       end
			%>
				</div>
				<div class='col-lg-4'>
<%
					if not @dentista.servicos.nil? then
						@dentista.servicos.each do |item| %>
				<%
						if num % num_p_col == 0 and num != 0 and col != 3 then
							col += 1
				%>
							</div>
							<div class='col-lg-4'>
				<%
						end
						num += 1
						ck_active = false
						if not @dentista.servicos.nil? then
							ck_active = @dentista.servicos.include?(item)
						end
				%>
						<div class="checkbox">
							<label><%=item%> </label>
						</div>
<% 
					end 
					end
					%>
				</div>
				
			</div>

		</div>
	</div>
</div>

<div class="col-lg-12">
	<div class="panel panel-default">
   		<div class="panel-heading">
        	<h3 class="panel-title">Equipe</h3>
        </div>
        <div class="panel-body">
        	
			<div class="form-group" id="div_equipe">
		<%
					
		
			if not @dentista.equipe.nil? and @dentista.equipe.size > 0 then
				@dentista.equipe.each do |eq|%>
					<div class="form-group">
						<%=eq%>
					</div>
					
		<%
				end
			end
		%>
					
		
			</div>
		</div>
	</div>
</div>

	
<div class="col-lg-12">
	<div class="panel panel-default">
   		<div class="panel-heading">
        	<h3 class="panel-title">Atendimento</h3>
        </div>
        <div class="panel-body">
        	
			<div class="form-group" id="div_atendimento">
		<%
				dias_semana_array = MainYetting.DIAS_SEMANA.map { |t| [t["desc"], t["id"]] }
				
				if not @dentista.at_normal.nil? and @dentista.at_normal.size > 0 then
					@dentista.at_normal.each do |horario|
%>
						
					<div class="col-lg-12">&nbsp;</div>
					<div>
						<div class="col-lg-4">
							<label>Dia:</label>
							<%=MainYetting.DIAS_SEMANA[horario.dia_sem]["desc"]%>
						</div>
						<div class="col-lg-3">
							<label>Abre:</label>
							<%=horario.h_open%>
						</div>
						<div class="col-lg-3">
							<label>Fecha:</label>
							<%=horario.h_close%>
						</div>
						<div class="col-lg-2">
							&nbsp;
						</div>
					</div>
<%  
					end
				end
%>
			</div>
		</div>
	</div>
</div>

<div class="col-lg-12">
	<div class="panel panel-default">
   		<div class="panel-heading">
        	<h3 class="panel-title">Atendimento de emergência</h3>
        </div>
        <div class="panel-body">
        	
			<div class="form-group" id="div_atendimento_emerg">
				<div class="col-lg-5">
					<label>Possui atendimento de emergência?</label>
				</div>
				<div class="col-lg-7">
		<%
					@value_at_emerg = 1
					if @dentista.at_emerg.nil? or @dentista.at_emerg.size <= 0 then
						@value_at_emerg = 0
					else
						if @dentista.at_emerg.size == 1 and (@dentista.at_emerg[0].h_open.nil? or @dentista.at_emerg[0].h_open.empty?) then
							@value_at_emerg = 0
						end
					end
		%>
					<%= @value_at_emerg == 0 ? "Não" : "Sim" %>
				</div>
				
				<div id="div_at_emergencia_interno">

<%
					if not @dentista.at_emerg.nil? and @dentista.at_emerg.size > 0 then
						@dentista.at_emerg.each do |horario|%>
							
					<div class="col-lg-12">&nbsp;</div>
					<div>
						<div class="col-lg-4">
							<label>Dia:</label>
							<%=horario.dia_sem%>
						</div>
						<div class="col-lg-3">
							<label>Abre:</label>
							<%=horario.h_open%>
						</div>
						<div class="col-lg-3">
							<label>Fecha:</label>
							<%=horario.h_close%>
						</div>
						<div class="col-lg-2">
							&nbsp;
						</div>
					</div>
<%
						end
					end%>
				</div>
			</div>
		</div>
	</div>
</div>
                
<div class="col-lg-12">
	
	<div class="panel panel-default">
   		<div class="panel-heading">
        	<h3 class="panel-title">Endereço</h3>
        </div>
        <div class="panel-body">
         
		         <div class="col-lg-6">
		         	<label>Rua:</label>
		         	<%=@dentista.address.street%>
		         </div>
		         <div class="col-lg-3">
		         	<label>Nr.:</label>
		         	<%=@dentista.address.number%>
		         </div>
		         <div class="col-lg-3"> 
		         	<label>Comp.:</label>
		         	<%=@dentista.address.complement%>
		 		 </div>
		 		 <div class="col-lg-12">&nbsp;</div>
		         <div class="col-lg-6">
		         	<label>Bairro:</label>
		         	<%=@dentista.address.neighborhood%>
		         </div>
		         <div class="col-lg-6">
		         	<label>CEP:</label>
		         	<%=@dentista.address.zip_code%>
		         </div>
		         <div class="col-lg-12">&nbsp;</div>
		         <div class="col-lg-6">
		         	<label>Estado:</label>
		         	<%=@dentista.address.state%>
		         </div>
		         <div class="col-lg-6">
		         	<label>Cidade:</label>
		         	<%=@dentista.address.city%>
		         </div>
		</div>
	</div>
</div>

<div class="col-lg-12">
	<div class="panel panel-default">
   		<div class="panel-heading">
        	<h3 class="panel-title">Promoção</h3>
        </div>
        <div class="panel-body">
        	
			<div class="form-group">
				<div class="col-lg-4">
					<label>Dentista com Promoção?</label>
				</div>
				<div class="col-lg-8">
					<%=(@dentista.promocao.nil? or @dentista.promocao.perc.nil?) ? "Não" : "Sim" %>
				</div>
			</div>
			<div class="col-lg-12">&nbsp;</div>
			<% if not (@dentista.promocao.nil? or @dentista.promocao.perc.nil?) then %>
			<span id="div_input_promocao">
			         <div class="col-lg-6">
			         	<label>Percentual</label>
			         	<%=  @dentista.promocao.perc %>%
			         </div>
			         <div class="col-lg-6">
			         	<label>Serviço</label>
			         	<%=  @dentista.promocao.servico %>
			         </div>
			</span>
			<%end%>
		</div>
	</div>
</div>
<div class="col-lg-12"><hr></div>

<div class="col-lg-12">
	
	<div class="panel panel-default">
   		<div class="panel-heading">
        	<h3 class="panel-title">Fotos </h3>
        </div>
        <div class="panel-body">
	<%
			@item_foto  = file_field 'dentista', 'pictures', name: 'dentista[pictures][]'
			if not @dentista.pictures.nil? and @dentista.pictures.size > 0 then
				@dentista.pictures.each do |f| %>
					<div style="float: left" class="text-center"><%=image_tag(f.picture, style: "max-height: 200px;")%>
					</div>
	<%
				end
			end
			%>
		</div>
	</div>
</div>