config/routes.rb
Rails.application.routes.draw do

  root :to =>  'site#home_new'
  get  '/:name/:id.html'          => 'site#home_new', :as => :site_home_dentista

 # root :to => "static#index_for_now"
  
  devise_for :dentists, path: "dentista", 
    controllers: { sessions: "dentist/sessions", registrations: 'dentist/registrations' },   
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
        unlock: 'unlock', registration: 'register', sign_up: 'sign_up' } do
    
    authenticated :dentists do
      root 'dentists/registrations#edit', as: :authenticated_root #'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'dentists/sessions#new', as: :unauthenticated_root
    end
  end
  
  get  'dentista/payment/process/:dentista_id'          => 'dentist/payment#process_payment', :as => :payment_process_payment
  post  'dentista/payment/update_status'   => 'dentist/payment#update_status', :as => :payment_update_status
  get  'dentista/payment/redo_payment/:dentista_id'   => 'dentist/payment#redo_payment', :as => :redo_payment
  patch  'dentista/payment/process_redo_payment'   => 'dentist/payment#process_redo_payment', :as => :process_redo_payment

  devise_for :users
  
  devise_scope :user do
    authenticated :user do
      root 'admin/admin#index', as: :authenticated_root #'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  namespace :api do
    namespace :v1 do
     
      get  'dentista/:dentista_id'                    => 'dentistas#get'
      get  'dentistas/find_near'                      => 'dentistas#find_near'
      get  'dentistas/cidades'                        => 'dentistas#get_cities'
      get  'dentistas/bairros'                        => 'dentistas#get_neighborhood'
      get  'dentistas/servicos'                       => 'dentistas#get_servicos'
      get  'dentistas/find_filter'                    => 'dentistas#find_filter' 
      get  'nr_dentistas'                             => 'dentistas#count'

      get  'dica/get_all'                             => 'dicas#get_ultimas_dicas' 
      
    end
  end
   
   
  namespace :admin do
    get '' => 'admin#index' 
    get 'admin/index'
    
    #dentista
    get     'dentista' => 'dentista#index'
    get     'dentista/new'
    post    'dentista/create'
    get     'dentista/:id' => 'dentista#show', as: 'dentista_show'
    get     'dentista/:id/edit' => 'dentista#edit', as: 'dentista_edit'
    patch   'dentista/:id' => 'dentista#update', as: 'dentista_update_patch'
    put     'dentista/:id' => 'dentista#update', as: 'dentista_update_put'
    delete  'dentista/:id' => 'dentista#destroy', as: 'dentista_delete' 
    delete     'dentista/foto/:id/:id_image' => 'dentista#delete_foto', as: 'dentista_delete_foto' 
    
    #dica
    get     'dica' => 'dica#index'
    get     'dica/new'
    post    'dica/create'
    get     'dica/:id' => 'dica#show', as: 'dica_show'
    get     'dica/:id/edit' => 'dica#edit', as: 'dica_edit'
    patch   'dica/:id' => 'dica#update', as: 'dica_update_patch'
    put     'dica/:id' => 'dica#update', as: 'dica_update_put'
    delete  'dica/:id' => 'dica#destroy', as: 'dica_delete'
    
  end
end

app/models/payment.rb
class Payment
  include Mongoid::Document
  include Mongoid::Timestamps
  
  before_create :assign_id

  field :_id,             type: Integer
  field :value,           type: Float
  field :type,            type: String
  field :boleto_url,      type: String
  field :transaction_id,  type: String
  
  embeds_many :payment_status
  belongs_to :dentist
  
private 
    def assign_id
      self._id = Sequence.generate_id(:payment)
    end 
end

app/controllers/dentist/confirmations_controller.rb
class Dentist::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/dentist/omniauth_callbacks_controller.rb
class Dentist::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/dentist/passwords_controller.rb
class Dentist::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/dentist/payment_controller.rb
class Dentist::PaymentController < ApplicationController
  include Dentistas::PaymentHelpers
 
  layout :resolve_layout

  skip_before_filter :verify_authenticity_token, :only => :update_status

  #force_ssl only: [:redo_payment,:process_redo_payment]

  def resolve_layout
    case action_name
    when "process_payment"
      "application"
    else
      "blank_layout"
    end
  end
  
  def redo_payment
    @dentista = Dentist.find(params[:dentista_id])
  end
  
  def process_redo_payment
    @dentista = Dentist.find(params[:dentist][:dentista_id])
    if @dentista.update(redo_params)
      value = Dentistas::PaymentHelpers::get_value(@dentista.plano)
      payment(@dentista, value, params)
      redirect_to root_path(:msg => "redo Pagamento")
    else
      flash["alert alert-danger"] = I18n.t(:error_default_msg)
      redirect_to redo_payment_path(@dentista)
    end
    
  end
  
  def update_status
    transaction_id = params[:id]
    status = params[:current_status]
    if not transaction_id.nil? then
      payment = Payment.where(:transaction_id => transaction_id).first
      #faz update do status
      payment_status = PaymentStatus.new
      payment_status.dt = Time.now
      payment_status.status = status # status da transação
      payment.payment_status << payment_status
      payment.save
      @dentista = Dentist.find(payment.dentist_id)
      if status == MainYetting.PAYMENT_STATUS_PAID then
        if @dentista.plano == MainYetting.PLANO_ANUAL then
          @dentista.dt_expiration_date = Date.today() + 12.months
        else
          @dentista.dt_expiration_date = Date.today() + 6.months
        end

        @dentista.save
        send_access_email(@dentista, payment)
      elsif status == MainYetting.PAYMENT_STATUS_REFUSED
        
        send_refused_status(@dentista, payment, status)
      else
        #puts "**** send_update_status #{@dentista.id}"
        #send_update_status(@dentista, payment, status)
      end
    end
  end
  
  def send_refused_status(dentista, payment, status)
    Thread.new do
      DentistaMailer.payment_refused(dentista, payment, status).deliver!
    end
  end
  
  def send_update_status(dentista, payment, status)
    Thread.new do
      DentistaMailer.update_status(dentista, payment, status).deliver!
    end
  end

  def process_payment
    id = params[:dentista_id]
    if not id.nil? then
      @dentista = Dentist.find(id)
           
      Thread.new do
        payment = Payment.where(:dentist_id => @dentista.id).last
        DentistaMailer.payment_process(@dentista, payment).deliver!
      end
    
    end
  end
  
private

  def redo_params
    params.require(:dentist).permit(:plano)
  end
  
  def send_access_email(dentista, payment)
    generated_password = Devise.friendly_token.first(8)
    dentista.password = generated_password

    Thread.new do
      DentistaMailer.payment_confirmed(dentista, generated_password).deliver!
    end
    dentista.save
  end

end

app/controllers/dentist/registrations_controller.rb
class Dentist::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  
  #force_ssl only: [:new,:create]
  
  skip_before_filter  :verify_authenticity_token
  
  layout :resolve_layout

  def resolve_layout
    case action_name
    when "new", "edit", "create", "update"
      "blank_layout"
    else
      "application"
    end
  end

  include Dentistas::PaymentHelpers

  def after_sign_up_path_for(resource)
    root_path(:msg => "Cadastro efetuado")
  end

  def after_update_path_for(resource)
    edit_dentist_registration_path(resource)
  end
    
  def edit
    flash.clear
    super    
  end
  
  def new
    flash.clear
    super
  end
  
  # POST /resource
  def create
    pwd = SecureRandom.hex(8)
    params[:dentist][:password] = pwd
    params[:dentist]["password_confirmation"] = pwd

    build_resource(sign_up_params) 
    flash.clear
    
    if params["accept_termos"].nil? or params["accept_termos"] != "on" then
      flash["alert alert-danger"] = I18n.t(:error_termos_de_uso_nao_aceito)
      render "new"
    else
      super
      if resource.errors.nil? or resource.errors.empty? then
        value = Dentistas::PaymentHelpers::get_value(resource.plano)
        payment(resource, value, params)
        Thread.new do
          payment = Payment.where(:dentist_id => resource.id).last
          DentistaMailer.payment_process(resource, payment).deliver!
        end
        sign_out
      else
        #erro cadastro não realizado
      end
     end
  end

  def edit
    @dentista = current_dentist
    build_dentista(@dentista)
    super
    flash.clear  
    
  end

  def build_dentista(dentista)
      if dentista.address.nil? then
        dentista.address = Address.new
      end
      if dentista.promocao.nil? then
        dentista.promocao = Promocao.new
      end
      if dentista.at_normal.nil? or dentista.at_normal.size <= 0  then
        dentista.at_normal.build
      end
    
      if dentista.at_emerg.nil? or dentista.at_emerg.size <= 0  then
        dentista.at_emerg.build
      end
    end


  def dentista_params
    params.require(:dentist).permit(:_id, :nome, :site, :email, :profile, :icon, :destaque, :phones => [], :equipe => [], :servicos => [],
    address: [:street, :number, :complement, :neighborhood, :zip_code, :city, :state], promocao: [:perc, :servico], at_normal: [:dia_sem, :h_open, :h_close], at_emerg: [:dia_sem, :h_open, :h_close])
  end
  
  def update
    @dentista = current_dentist
    
    params_update = dentista_params
    has_promo = params[:dentist][:has_promo]
    if has_promo.nil? or 
      (not has_promo.nil? and has_promo == "0") then
      params_update[:promocao] = nil
    end
    
    params[:dentist].delete :has_promo
    
    if not params[:dentist][:has_at_emerg].nil? and params[:dentist][:has_at_emerg] == "0" then
      params_update[:at_emerg] = nil
    end
    params[:dentist].delete :has_at_emerg
    
    if params[:dentist][:at_emerg].nil? then
      params_update[:at_emerg] = nil
    end

    if @dentista.dt_expiration_date >= Date.today() and 
      not @dentista.address.nil? and not @dentista.address.coordinates.nil?  and 
      not @dentista.address.coordinates.empty? then
      params_update[:active] = true
    else
      params_update[:active] = false
    end

    if @dentista.update(params_update)
      
      if params[:images]
        #===== The magic is here ;)
        params[:images].each { |image|
          @dentista.pictures.create(picture: image)
        }
      end
      
      flash["alert alert-success"] = "Alteração efetuada com sucesso."
    else
      set_error(@dentista, "Ocorreu algum erro.")
    end

    build_dentista(@dentista)
    render 'edit'
  end
  
  def sign_up_params
    params.require(:dentist).permit(:nome, :email, :plano, :password, :password_confirmation, :phones => [])
  end
end

app/controllers/dentist/sessions_controller.rb
class Dentist::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
 before_filter :sign_out_pre_login, only: [:new]

  layout :resolve_layout

  def resolve_layout
    case action_name
    when "new"
      "blank_layout"
    else
      "application"
    end
  end
  

  def edit     
    flash.clear
    super
  end
  # GET /resource/sign_in
  def new     
    sign_out(current_dentist)
    super
  end

  def sign_out_pre_login
    sign_out(current_dentist)
  end
  def after_sign_in_path_for(resource)
    edit_dentist_registration_path(resource)
  end

  # POST /resource/sign_in
  def create
    super
    if not dentist_signed_in? then
      flash["alert alert-danger"] = I18n.t(:error_default_msg)
    else
      #puts ">>>>>> signed"
    end
  end

  def destroy
    super
    redirect_to root_path
  end
  
  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/dentist/unlocks_controller.rb
class Dentist::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/dentist/dentist_helper.rb
module Dentist::DentistHelper
  
  def delete_foto_helper(dentista, id_image)
    if not dentista.nil? and not dentista.pictures.nil? then
      dentista.pictures.each do |pic|
        if pic._id == id_image
            if dentista.pictures.delete(pic) then
              return true
            else
              if not obj.errors.nil? then
                flash["alert alert-danger"] = obj.errors.full_messages
              else
                flash["alert alert-danger"] = msg
              end
            end
        end
      end 
    end
    
    return false
  end
  
end

app/helpers/dentist/payment_helper.rb
module Dentist::PaymentHelper
  
  
end

app/views/dentist/payment/payment_form.html.erb
<div class='form-group'>
	<label class='control-label col-md-2 col-md-offset-2' for='id_email'>Modo de Pagamento</label>
	<div class='col-md-6'>
		<div class='form-group'>
			<div class='col-md-6'>
				<select class='form-control' id='payment_type'  name="payment_type">
					<option value="credit_card">Cartão de Crédito</option>
					<option value="boleto">Boleto</option>
				</select>
			</div>
		</div>
	</div>
</div>

<div class='form-group'>
	<label class='control-label col-md-2 col-md-offset-2' for='dentist[plano]'>Plano Escolhido</label>
	<div class='col-md-6'>
		<div class='form-group'>
			<div class='col-md-6'>
				<select class='form-control' id='dentist[plano]' name='dentist[plano]'>
					
					<option value='anual' selected="selected">Anual</option>
					<option value='semestral'>Semestral</option>
				</select>
			</div>
		</div>
	</div>
	<div class='col-md-4'></div>
	<div class='col-md-8'>
		<div class='form-group internal'>
			<p>
				Assinatura Semestral: R$ 200,00
			</p>
			<p>
				Assinatura Anual: R$ 400,00
			</p>
		</div>
	</div>
</div>
<div class='form-group' id="form_credit_card">
	<label class='control-label col-md-2 col-md-offset-2' for='id_adults'>Dados do Cartão</label>
	<div class='col-md-8'>
		<div class='col-md-8'>
			<div class='form-group internal'>
				<input class='form-control' id='card_holder_name' placeholder='Nome' type='text' >
			</div>
		</div>
	</div>
	<div class='col-md-4'></div>
	<div class='col-md-8'>
		<br>
		<div class='col-md-5'>
			<div class='form-group internal'>
				<input class='form-control' id='card_number' name='card_number' placeholder='Número do Cartão' type='text'>
			</div>
		</div>
		<div class='col-md-3'>
			<div class='form-group internal' style="padding-left: 5px;">
				<input class='form-control' id='card_cvv' placeholder='Código de Segurança' type='text'>
			</div>
		</div>
	</div>
	<div class='col-md-4'></div>
	<div class='col-md-8'>
		<br>
		<div class='col-md-2'>
			<div class='form-group internal'>
				<select class='form-control' id='id_equipment'>
					<option value="credit_card">Visa</option>
					<option value="boleto">Master</option>
				</select>

			</div>
		</div>
		<div class='col-md-3'>
			<div class='form-group internal' style="padding-left: 5px;">
				<input class='form-control' id='card_expiration_month' placeholder='Mês de expiração' type='text'>
			</div>
		</div>
		<div class='col-md-3'>
			<div class='form-group internal' style="padding-left: 5px;">
				<input class='form-control' id='card_expiration_year' placeholder='Ano de expiração' type='text'>
			</div>
		</div>
	</div>
	<div class='col-md-4'></div>
	<div class='col-md-8'>
		<br>
		<div id="field_errors"></div>
	</div>
</div>

<script>
	$(document).ready(function() {// quando o jQuery estiver carregado...
		$(":input").inputmask();
		$('#card_expiration_month').inputmask({
			mask : '99'
		});
		$('#card_expiration_year').inputmask({
			mask : '9999'
		});
		$('#card_cvv').inputmask({
			mask : '999'
		});
		$('#card_number').inputmask({
			mask : '9999-9999-9999-9999'
		});
		
		
		PagarMe.encryption_key = "<%=MainYetting.PAGAR_ME_ENC_KEY%>";


			
		var form = $("#<%= form_id%>");

		form.submit(function(event) {// quando o form for enviado...
		// inicializa um objeto de cartão de crédito e completa
		// com os dados do form

		

		var creditCard = new PagarMe.creditCard();
		creditCard.cardHolderName = $("#card_holder_name").val();
		creditCard.cardExpirationMonth = $("#card_expiration_month").val();
		creditCard.cardExpirationYear = $("#card_expiration_year").val();
		creditCard.cardNumber = $("#card_number").val();
		creditCard.cardCVV = $("#card_cvv").val();
		
		// pega os erros de validação nos campos do form
		var fieldErrors = creditCard.fieldErrors();

		//Verifica se há erros
		var hasErrors = false;
		for (var field in fieldErrors) {
		hasErrors = true;
		alert("field: " + field);
		break;

		}

		if (hasErrors) {
		// realiza o tratamento de errors
		alert("erro: " + fieldErrors);
		} else {
		// se não há erros, gera o card_hash...
		creditCard.generateHash(function(cardHash) {
		// ...coloca-o no form...
		form.append($('<input type="hidden" name="card_hash">').val(cardHash));
		// e envia o form
		form.get(0).submit();
		});
		}

		return false;
		});
		});
		
	$( "#payment_type" )
	  .change(function () {
	    if ("boleto" == $( "#payment_type" ).val()) {
	    	$("#form_credit_card").hide()
	    } else {
	    	$("#form_credit_card").show()
	    }
	  })
	  .change();
</script>

app/views/dentist/payment/process_payment.html.erb
<%
if @dentista.nil? then
%>
erro
<%
else
%>
<%=@dentista.nome%>,<br>
Seu pagamento está em processamento. <br>
Assim que finalizar vc receberá um email com seu usuário e senha para realizar o preenchimento dos dados do seu consultório.

<%end%>

app/views/dentist/payment/redo_payment.html.erb
<!DOCTYPE html>
<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Dentistas App</title>
	<meta name="description" content="O primeiro serviço mobile voltado para a área odontológica do Brasil.">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
	<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
	<link rel="manifest" href="/manifest.json">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
	<meta name="theme-color" content="#ffffff">

	<meta property="og:title" content="Dentistas APP" />
	<meta property="og:site_name" content="Dentistas APP"/>
	<meta property="og:url" content="http://www.dentistasapp.com" />
	<meta property="og:description" content="O primeiro serviço mobile voltado para a área odontológica do Brasil." />

	<link href='//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css' rel='stylesheet' type='text/css'>
	<link href='//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/1.8/css/bootstrap-switch.css' rel='stylesheet' type='text/css'>
	<script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js' type='text/javascript'></script>
	<script src='//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/1.8/js/bootstrap-switch.min.js' type='text/javascript'></script>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script src='/assets/js/vendor/bootstrap.min.js' type='text/javascript'></script>
	<script src='/assets/js/vendor/jquery.inputmask.bundle.min.js' type='text/javascript'></script>
	<script src="https://pagar.me/assets/pagarme-v2.min.js"></script>
	<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

	<link rel="stylesheet" href="/assets/css/form.css">

	<meta charset="UTF-8">
</head>
<body>
	<div>
		<%= form_for @dentista, url: process_redo_payment_path, :html => { :id => "redo_payment_form",class:'form-horizontal', role:'form' } do |f| %>
		<%= f.hidden_field :dentista_id, value: @dentista.id %>
		<div class='container'>
			<div class='panel-heading'>
				<div class='bg'>
					<h4><img src="/assets/img/logo-flat.png" width="92" height="88">Refazer pagamento</h4>
				</div>
				<div class="dialog-panel" id="texto">
					<p>
						Infelizmente, enfrentamos problemas para confirmar o seu pagamento. Para tentar novamente, basta selecionar abaixo seu período de assinatura, que pode ser semestral ou anual. Selecionado o período, preencha seus dados e confirme o pagamento. Em menos de 24 horas, você receberá um e-mail com as instruções para criar seu perfil dentro do aplicativo.
					</p>
				</div>

				<div class='panel-body'>

					<div class='form-group' id='div_error'>
						&nbsp;

						<% flash.each do |name, msg| -%>
						<%= content_tag :div, msg, class: name %>
						<% end %>
					</div>

					<%= render :template => "dentist/payment/payment_form", :locals => {:form_id => "redo_payment_form"} %>

					<div class='form-group'>
						<label class='control-label col-md-2 col-md-offset-2' for='id_termos'>Concordo com os termos </label>

						<div class='col-md-8 form-group internal'>

							<div class='make-switch' data-off-label='Não' data-on-label='Sim' id='id_termos_switch'>
								<input id='accept_termos' name='accept_termos' type='checkbox' >
							</div>
							<div id="accept_termos_error"></div>
						</div>
					</div>
					<div class='form-group'>
						<div class='col-md-offset-4 col-md-3'>
							<button class='btn-lg btn-primary' type='button' onclick="javascript:validate_form()" >
								Continuar
							</button>

						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Modal -->
		<div class="modal fade" id="confirm_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
						<h4 class="modal-title" id="myModalLabel">Confirmar Pagamento</h4>
					</div>
					<div class="modal-body" id="modal-message">
						Você está assinando um plano X e o valor a ser debitado é de Y.
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary">
							Confirmar Pagamento
						</button>
					</div>
				</div>
			</div>
		</div>

		<% end %>
	</div>
	<script>
		function show_modal() {
			plano = $("#dentist\\[plano\\]").val();
			valor = "R$200,00";
			if (plano == "anual") {
				valor = "R$400,00";
			}
			html = "Você está assinando um plano " + plano + " e o valor a ser debitado é de " + valor + "."
			$("#modal-message").html(html);
			$('#confirm_modal').modal();
		}

		function validate_form() {
			var valid = $('form').validate().form()
			if (valid) {
				show_modal();
			}
		}


		$(document).ready(function() {
			$(":input").inputmask();

			$("#id_codigo_seguranca").inputmask({
				mask : '999'
			})

			jQuery.validator.addMethod("checkboxes", function(value, element) {
				return $("#" + element.name).is(':checked');
			});

			$('form').validate({
				ignore : [],
				rules : {
					accept_termos : {
						"checkboxes" : true
					}
				},
				messages : {
					"accept_termos" : {
						required : "Para realizar o cadastro você deve concordar com os termos",
						"checkboxes" : "Para realizar o cadastro você deve concordar com os termos"
					}
				},
				highlight : function(element) {
					$(element).closest('.form-group').addClass('has-error');
				},
				unhighlight : function(element) {
					$(element).closest('.form-group').removeClass('has-error');
				},
				errorElement : 'span',
				errorClass : 'help-block',
				errorPlacement : function(error, element) {
					var name_element = '#' + element.attr('name') + '_error';

					parent_element = $(name_element)
					if (parent_element.length) {
						error.insertAfter($(parent_element));
					} else if (element.parent('.input-group').length) {
						error.insertAfter(element.parent());
					} else {
						error.insertAfter(element);
					}
				}
			});

			jQuery.extend(jQuery.validator.messages, {
				required : "Campo obrigatório.",
				remote : "Valor inválido.",
				email : "Email inválido.",
				url : "URL inválida.",
				date : "Data inválida.",
				dateISO : "Data inválida (ISO).",
				number : "Número inválido.",
				digits : "Somente digitos são válidos.",
				creditcard : "Número de cartão inválido.",
				equalTo : "Entre o mesmo valor novamente.",
				accept : "Entre com um valor com uma extensão válida.",
				maxlength : jQuery.validator.format("Número máximo de caracteres {0}."),
				minlength : jQuery.validator.format("Deve ter no mínimo {0} caracteres."),
				rangelength : jQuery.validator.format("Entre com um valor entre {0} e {1}."),
				range : jQuery.validator.format("Entre com um valor entre {0} e {1}."),
				max : jQuery.validator.format("Entre com um valor menor que {0}."),
				min : jQuery.validator.format("Entre com um valor  maior que {0}.")
			});

		});

	</script>
</body>

</html>

app/views/dentist/payment/update_status.html.erb
ok