config/routes.rb
Rails.application.routes.draw do

  root :to =>  'site#home_new'
  get  '/:name/:id.html'          => 'site#home_new', :as => :site_home_dentista

 # root :to => "static#index_for_now"
  
  devise_for :dentists, path: "dentista", 
    controllers: { sessions: "dentist/sessions", registrations: 'dentist/registrations' },   
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
        unlock: 'unlock', registration: 'register', sign_up: 'sign_up' } do
    
    authenticated :dentists do
      root 'dentists/registrations#edit', as: :authenticated_root #'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'dentists/sessions#new', as: :unauthenticated_root
    end
  end
  
  get  'dentista/payment/process/:dentista_id'          => 'dentist/payment#process_payment', :as => :payment_process_payment
  post  'dentista/payment/update_status'   => 'dentist/payment#update_status', :as => :payment_update_status
  get  'dentista/payment/redo_payment/:dentista_id'   => 'dentist/payment#redo_payment', :as => :redo_payment
  patch  'dentista/payment/process_redo_payment'   => 'dentist/payment#process_redo_payment', :as => :process_redo_payment

  devise_for :users
  
  devise_scope :user do
    authenticated :user do
      root 'admin/admin#index', as: :authenticated_root #'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  namespace :api do
    namespace :v1 do
     
      get  'dentista/:dentista_id'                    => 'dentistas#get'
      get  'dentistas/find_near'                      => 'dentistas#find_near'
      get  'dentistas/cidades'                        => 'dentistas#get_cities'
      get  'dentistas/bairros'                        => 'dentistas#get_neighborhood'
      get  'dentistas/servicos'                       => 'dentistas#get_servicos'
      get  'dentistas/find_filter'                    => 'dentistas#find_filter' 
      get  'nr_dentistas'                             => 'dentistas#count'

      get  'dica/get_all'                             => 'dicas#get_ultimas_dicas' 
      
    end
  end
   
   
  namespace :admin do
    get '' => 'admin#index' 
    get 'admin/index'
    
    #dentista
    get     'dentista' => 'dentista#index'
    get     'dentista/new'
    post    'dentista/create'
    get     'dentista/:id' => 'dentista#show', as: 'dentista_show'
    get     'dentista/:id/edit' => 'dentista#edit', as: 'dentista_edit'
    patch   'dentista/:id' => 'dentista#update', as: 'dentista_update_patch'
    put     'dentista/:id' => 'dentista#update', as: 'dentista_update_put'
    delete  'dentista/:id' => 'dentista#destroy', as: 'dentista_delete' 
    delete     'dentista/foto/:id/:id_image' => 'dentista#delete_foto', as: 'dentista_delete_foto' 
    
    #dica
    get     'dica' => 'dica#index'
    get     'dica/new'
    post    'dica/create'
    get     'dica/:id' => 'dica#show', as: 'dica_show'
    get     'dica/:id/edit' => 'dica#edit', as: 'dica_edit'
    patch   'dica/:id' => 'dica#update', as: 'dica_update_patch'
    put     'dica/:id' => 'dica#update', as: 'dica_update_put'
    delete  'dica/:id' => 'dica#destroy', as: 'dica_delete'
    
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Dentistas App</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="wrapper">

			<!-- Navigation -->
			<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
				
<% 		
			if user_signed_in? then
%>
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/admin">Admin</a>
				</div>
				<!-- Top Menu Items -->
				<ul class="nav navbar-right top-nav">
					
					<li class="dropdown">
					
<% 		
						if user_signed_in? then
%>
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <John Smith><%=current_user.email%> <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									 <%= link_to 'Logout', destroy_user_session_path(), method: :delete %>
								</li>
							</ul>
<%
						end
%>
					</li>
				</ul>
				<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav side-nav">
						<li class="active">
							<a href="javascript:;" data-toggle="collapse" data-target="#dentistas-collapse"><i class="fa fa-fw fa-arrows-v"></i> Dentistas <i class="fa fa-fw fa-caret-down"></i></a>
	                        <ul id="dentistas-collapse" class="collapse">
	                            <li>
	                                <%= link_to 'Listar', admin_dentista_path() %> 
	                            </li>
	                            <li>
	                                <%= link_to 'Cadastrar', admin_dentista_new_path() %>
	                            </li>
	                        </ul>
						</li>
						<li class="active">
							<a href="javascript:;" data-toggle="collapse" data-target="#dica-collapse"><i class="fa fa-fw fa-arrows-v"></i> Dicas <i class="fa fa-fw fa-caret-down"></i></a>
	                        <ul id="dica-collapse" class="collapse">
	                            <li>
	                                <%= link_to 'Listar', admin_dica_path() %> 
	                            </li>
	                            <li>
	                                <%= link_to 'Cadastrar', admin_dica_new_path() %>
	                            </li>
	                        </ul>
						</li>
						
					</ul>
				</div>
				<!-- /.navbar-collapse -->
				
<%
			 	end 
%>
			</nav>


	        <div id="page-wrapper">
	
	            <div class="container-fluid">

					<%= yield %>
			
	            </div>
	            <!-- /.container-fluid -->

	        </div>
	        <!-- /#page-wrapper -->
		</div>
		<!-- /#page-wrapper -->
	</body>
</html>
<% flash.clear %>

app/views/layouts/blank_layout.html.erb
<%= yield %>
<% flash.clear %>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
	<!--<![endif]-->

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title> Dentistas APP </title>
		<meta name="description" content="O primeiro serviço mobile voltado para a área odontológica do Brasil.">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="icon" href="favicon.ico">

		<!-- Pixeden icon font -->
		<link rel="stylesheet" href="/assets/fonts/pe-icon-7-filled/css/pe-icon-7-filled.css">
		<link rel="stylesheet" href="/assets/fonts/pe-icon-social/css/Pe-icon-social.css">
		<link rel="stylesheet" href="/assets/fonts/pe-icon-7-filled/css/helper.css">

		<link rel="stylesheet" href="/assets/css/vendor/bootstrap.min.css">
		<link rel="stylesheet" href="/assets/css/vendor/animate-custom.css">
		<link rel="stylesheet" href="/assets/css/main.min.css">
		<script src="/assets/js/vendor/modernizr-2.8.3.min.js"></script>

		<link href='//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/1.8/css/bootstrap-switch.css' rel='stylesheet' type='text/css'>
		<script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js' type='text/javascript'></script>

	</head>

	<body class="<%= yield(:class_body) %>">
		
		<%= yield %>
		
	</body>
</html>


<% flash.clear %>